# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CREATE UAS
email: uas@createunsw.com.au
description: "CREATE Unmanned Aerial Systems is a UNSW-based group, whose aim is produce and test autonomous aerial vehicles and systems."
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
permalink: /:categories/:title/
future: true
plugins: [jekyll-paginate, kramdown, jekyll-seo-tag, jekyll-sitemap]
markdown: kramdown
include: ['_pages']

collections:
  _people:
    output: true
    permalink: /team/:title/
  _projects:
    output: true
    permalink: /projects/:title/
